'use client';
import { useEffect, useMemo, useRef, useState } from 'react';

type Article = { id:string; title:string; url:string; source:string; sourceType:string; publishedAt:string; fetchedAt:string; category:string; summary:string; whyItMatters:string; readingMinutes:number; importance:number; language:string; tags:string[]; duplicateGroup:string|null; originalTitle:string; filterFlags:string[]; aiGenerated:boolean };
type Config = { site:{title:string;subtitle:string;endMessage:string}; categories:string[]; limits:{total:number;top:number} };
type NewsData = { updatedAt:string; articles:Article[]; sourceStatus?:Record<string,string> };
type HiddenReason = '興味がない'|'煽りが強い'|'難しすぎる'|'同じ話題が多い'|'気分が悪くなる'|'その他';
const prefix = process.env.NEXT_PUBLIC_BASE_PATH ?? '';
const storage = { read:'emiko.read', saved:'emiko.saved', hidden:'emiko.hidden', mutedSources:'emiko.mutedSources', mutedKeywords:'emiko.mutedKeywords', theme:'emiko.theme', font:'emiko.font' };
function getList(key:string){ if(typeof window==='undefined')return [];try{return JSON.parse(localStorage.getItem(key)||'[]')}catch{return []} }
function getValue(key:string,fallback:string){return typeof window==='undefined'?fallback:(localStorage.getItem(key)||fallback)}
function formatDate(value:string){try{return new Intl.DateTimeFormat('ja-JP',{month:'numeric',day:'numeric',hour:'2-digit',minute:'2-digit'}).format(new Date(value))}catch{return '日時不明'}}
function safeUrl(value:string){try{const u=new URL(value);return ['http:','https:'].includes(u.protocol)?u.toString():'#'}catch{return '#'}}

export default function Home(){
  const [data,setData]=useState<NewsData|null>(null); const [config,setConfig]=useState<Config|null>(null);
  const [category,setCategory]=useState('すべて'); const [budget,setBudget]=useState<3|10|null>(null);
  const [read,setRead]=useState<string[]>(()=>getList(storage.read)); const [saved,setSaved]=useState<string[]>(()=>getList(storage.saved)); const [hidden,setHidden]=useState<Record<string,{reason:HiddenReason;at:string}>>(()=>typeof window==='undefined'?{}:JSON.parse(localStorage.getItem(storage.hidden)||'{}'));
  const [mutedSources,setMutedSources]=useState<string[]>(()=>getList(storage.mutedSources)); const [mutedKeywords,setMutedKeywords]=useState<string[]>(()=>getList(storage.mutedKeywords)); const [keyword,setKeyword]=useState('');
  const [theme,setTheme]=useState(()=>getValue(storage.theme,'light')); const [fontSize,setFontSize]=useState(()=>getValue(storage.font,'medium')); const [settingsOpen,setSettingsOpen]=useState(false); const [hideTarget,setHideTarget]=useState<Article|null>(null);
  const dialog=useRef<HTMLDialogElement>(null);
  useEffect(()=>{Promise.all([fetch(`${prefix}/config/site.json`).then(r=>r.json() as Promise<Config>),fetch(`${prefix}/data/news.json`).then(r=>r.json() as Promise<NewsData>)]).then(([c,d])=>{setConfig(c);setData(d)}).catch(()=>setData({updatedAt:new Date().toISOString(),articles:[]}))},[]);
  useEffect(()=>{document.documentElement.dataset.theme=theme;document.documentElement.dataset.font=fontSize},[theme,fontSize]);
  const visible=useMemo(()=>{let list=(data?.articles||[]).filter(a=>!hidden[a.id]&&!mutedSources.includes(a.source)&&!mutedKeywords.some(k=>(a.title+' '+a.summary+' '+a.tags.join(' ')).toLowerCase().includes(k.toLowerCase())));if(category==='保存した記事')list=list.filter(a=>saved.includes(a.id));else if(category!=='すべて')list=list.filter(a=>a.category===category);if(budget){let sum=0;list=list.filter(a=>{if(sum>=budget)return false;sum+=a.readingMinutes;return true})}return list},[data,hidden,mutedSources,mutedKeywords,category,budget,saved]);
  const top=useMemo(()=>visible.slice(0,config?.limits.top||3),[visible,config]);
  function persistList(key:string,value:string[],setter:(v:string[])=>void){setter(value);localStorage.setItem(key,JSON.stringify(value))}
  function toggleSaved(id:string){persistList(storage.saved,saved.includes(id)?saved.filter(x=>x!==id):[...saved,id],setSaved)}
  function markRead(id:string){if(!read.includes(id))persistList(storage.read,[...read,id],setRead)}
  function askHide(article:Article){setHideTarget(article);dialog.current?.showModal()}
  function confirmHide(reason:HiddenReason){if(!hideTarget)return;const next={...hidden,[hideTarget.id]:{reason,at:new Date().toISOString()}};setHidden(next);localStorage.setItem(storage.hidden,JSON.stringify(next));dialog.current?.close();setHideTarget(null)}
  function reset(){if(!confirm('保存・既読・ミュート・表示設定をすべて初期化しますか？'))return;Object.values(storage).forEach(k=>localStorage.removeItem(k));setRead([]);setSaved([]);setHidden({});setMutedSources([]);setMutedKeywords([]);setTheme('light');setFontSize('medium')}
  function ArticleActions({article}:{article:Article}){return <div className="actions"><button onClick={()=>toggleSaved(article.id)}>{saved.includes(article.id)?'保存済み':'保存'}</button><button onClick={()=>askHide(article)}>非表示</button><button onClick={()=>persistList(storage.mutedSources,[...new Set([...mutedSources,article.source])],setMutedSources)}>この情報源をミュート</button></div>}
  const title=config?.site.title||'恵美子新聞'; const subtitle=config?.site.subtitle||'煽られずに、世の中を知る。';
  return <main>
    <a className="skip" href="#news">ニュースへ移動</a>
    <header className="masthead"><div className="masthead__rule"/><div className="masthead__inner"><div><p className="eyebrow">PERSONAL DAILY · TOKYO</p><h1>{title}</h1><p className="subtitle">{subtitle}</p></div><div className="datebox"><span>{new Intl.DateTimeFormat('ja-JP',{month:'long',day:'numeric',weekday:'long'}).format(new Date())}</span><small>{data?`最終更新 ${formatDate(data.updatedAt)}`:'読み込み中'}</small><button onClick={()=>setSettingsOpen(!settingsOpen)} aria-expanded={settingsOpen}>表示とミュート設定</button></div></div></header>
    {settingsOpen&&<aside className="settings" aria-label="表示とミュート設定"><div><b>表示時間</b><button className={budget===3?'active':''} onClick={()=>setBudget(budget===3?null:3)}>3分で読む</button><button className={budget===10?'active':''} onClick={()=>setBudget(budget===10?null:10)}>10分で読む</button></div><div><b>文字サイズ</b>{['small','medium','large'].map((s,i)=><button key={s} className={fontSize===s?'active':''} onClick={()=>{setFontSize(s);localStorage.setItem(storage.font,s)}}>{['小','中','大'][i]}</button>)}</div><div><b>表示</b><button onClick={()=>{const next=theme==='light'?'dark':'light';setTheme(next);localStorage.setItem(storage.theme,next)}}>{theme==='light'?'ダークモード':'ライトモード'}</button><button onClick={reset}>設定を初期化</button></div><form onSubmit={e=>{e.preventDefault();const k=keyword.trim();if(k){persistList(storage.mutedKeywords,[...new Set([...mutedKeywords,k])],setMutedKeywords);setKeyword('')}}}><label htmlFor="mute-keyword">キーワードをミュート</label><input id="mute-keyword" value={keyword} onChange={e=>setKeyword(e.target.value)} placeholder="例：選挙速報"/><button>追加</button></form>{(mutedKeywords.length>0||mutedSources.length>0)&&<div className="mute-list"><b>ミュート中</b>{mutedKeywords.map(k=><button key={k} onClick={()=>persistList(storage.mutedKeywords,mutedKeywords.filter(x=>x!==k),setMutedKeywords)}>「{k}」×</button>)}{mutedSources.map(s=><button key={s} onClick={()=>persistList(storage.mutedSources,mutedSources.filter(x=>x!==s),setMutedSources)}>{s} ×</button>)}</div>}</aside>}
    <section className="top-section" aria-labelledby="top-title"><div className="section-heading"><p>3分で、今日の輪郭</p><h2 id="top-title">今日これだけ</h2><span>重要な3件</span></div>{top.length?<div className="top-grid">{top.map((a,i)=><article className={`top-story ${read.includes(a.id)?'is-read':''}`} key={a.id}><p className="story-kicker"><span>0{i+1}</span>{a.category} · {a.source}</p><h3><a href={safeUrl(a.url)} target="_blank" rel="noopener noreferrer" onClick={()=>markRead(a.id)}>{a.title}</a></h3><p className="summary">{a.summary}</p><p className="why"><b>なぜ重要？</b>{a.whyItMatters}</p><footer><span>{a.readingMinutes}分で読む</span>{read.includes(a.id)&&<span>既読</span>}</footer><ArticleActions article={a}/></article>)}</div>:<p className="empty">条件に合う記事はありません。設定からミュートを解除できます。</p>}</section>
    <nav className="category-nav" aria-label="カテゴリー">{['すべて',...(config?.categories||[]),'保存した記事'].map(item=><button key={item} className={category===item?'active':''} onClick={()=>setCategory(item)}>{item}</button>)}</nav>
    <section className="news-list" id="news" aria-label="今日のニュース">{visible.map(a=><article className={`news-row ${read.includes(a.id)?'is-read':''}`} key={a.id}><div className="news-row__meta"><span>{a.category}</span><time dateTime={a.publishedAt}>{formatDate(a.publishedAt)}</time>{read.includes(a.id)&&<em>既読</em>}</div><div><h3><a href={safeUrl(a.url)} target="_blank" rel="noopener noreferrer" onClick={()=>markRead(a.id)}>{a.title}</a></h3><p>{a.summary}</p><small className="why-inline">なぜ重要？ {a.whyItMatters}</small><ArticleActions article={a}/></div><div className="news-row__source"><b>{a.source}</b><span>{a.readingMinutes}分</span><span>取得 {formatDate(a.fetchedAt)}</span></div></article>)}</section>
    <footer className="endmark"><span>本日の終点</span><h2>今日の分はここまでです。</h2><p>{config?.site.endMessage||'知らなくても困らないニュースまで追いかける必要はありません。'}</p></footer>
    <dialog ref={dialog} className="hide-dialog"><form method="dialog"><button className="dialog-close" aria-label="閉じる">×</button><p>この記事を非表示にする理由（任意）</p>{(['興味がない','煽りが強い','難しすぎる','同じ話題が多い','気分が悪くなる','その他'] as HiddenReason[]).map(r=><button type="button" key={r} onClick={()=>confirmHide(r)}>{r}</button>)}</form></dialog>
  </main>
}
